Fix

diff --git a/.github/workflows/baseimage.yml b/.github/workflows/baseimage.yml
--- a/.github/workflows/baseimage.yml
+++ b/.github/workflows/baseimage.yml
@@ -19,55 +19,76 @@ jobs:
     strategy:
       matrix:
         info:
-          - '{ "tag_prefix": "alpine-3.6",        "dockerfile": "Dockerfile.alpine",       "baseimage": "alpine:3.6" }'
-          - '{ "tag_prefix": "alpine-3.7",        "dockerfile": "Dockerfile.alpine",       "baseimage": "alpine:3.7" }'
-          - '{ "tag_prefix": "alpine-3.8",        "dockerfile": "Dockerfile.alpine",       "baseimage": "alpine:3.8" }'
-          - '{ "tag_prefix": "alpine-3.9",        "dockerfile": "Dockerfile.alpine",       "baseimage": "alpine:3.9" }'
-          - '{ "tag_prefix": "alpine-3.10",       "dockerfile": "Dockerfile.alpine",       "baseimage": "alpine:3.10" }'
-          - '{ "tag_prefix": "alpine-3.11",       "dockerfile": "Dockerfile.alpine",       "baseimage": "alpine:3.12" }'
-          - '{ "tag_prefix": "alpine-3.12",       "dockerfile": "Dockerfile.alpine",       "baseimage": "alpine:3.12" }'
-          - '{ "tag_prefix": "alpine-3.6-glibc",  "dockerfile": "Dockerfile.alpine-glibc", "baseimage": "alpine:3.6" }'
-          - '{ "tag_prefix": "alpine-3.7-glibc",  "dockerfile": "Dockerfile.alpine-glibc", "baseimage": "alpine:3.7" }'
-          - '{ "tag_prefix": "alpine-3.8-glibc",  "dockerfile": "Dockerfile.alpine-glibc", "baseimage": "alpine:3.8" }'
-          - '{ "tag_prefix": "alpine-3.9-glibc",  "dockerfile": "Dockerfile.alpine-glibc", "baseimage": "alpine:3.9" }'
-          - '{ "tag_prefix": "alpine-3.10-glibc", "dockerfile": "Dockerfile.alpine-glibc", "baseimage": "alpine:3.10" }'
-          - '{ "tag_prefix": "alpine-3.11-glibc", "dockerfile": "Dockerfile.alpine-glibc", "baseimage": "alpine:3.11" }'
-          - '{ "tag_prefix": "alpine-3.12-glibc", "dockerfile": "Dockerfile.alpine-glibc", "baseimage": "alpine:3.12" }'
-          - '{ "tag_prefix": "debian-8",          "dockerfile": "Dockerfile.debian",       "baseimage": "debian:jessie-slim" }'
-          - '{ "tag_prefix": "debian-9",          "dockerfile": "Dockerfile.debian",       "baseimage": "debian:stretch-slim" }'
-          - '{ "tag_prefix": "debian-10",         "dockerfile": "Dockerfile.debian",       "baseimage": "debian:buster-slim" }'
-          - '{ "tag_prefix": "ubuntu-16.04",      "dockerfile": "Dockerfile.debian",       "baseimage": "ubuntu:xenial" }'
-          - '{ "tag_prefix": "ubuntu-18.04",      "dockerfile": "Dockerfile.debian",       "baseimage": "ubuntu:bionic" }'
+          - '{ "tag_prefix": "alpine-3.6",        "baseimage": "alpine:3.6",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.7",        "baseimage": "alpine:3.7",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.8",        "baseimage": "alpine:3.8",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.9",        "baseimage": "alpine:3.9",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.10",       "baseimage": "alpine:3.10",         "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.11",       "baseimage": "alpine:3.12",         "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.12",       "baseimage": "alpine:3.12",         "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.6-glibc",  "baseimage": "alpine:3.6",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.7-glibc",  "baseimage": "alpine:3.7",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.8-glibc",  "baseimage": "alpine:3.8",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.9-glibc",  "baseimage": "alpine:3.9",          "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.10-glibc", "baseimage": "alpine:3.10",         "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.11-glibc", "baseimage": "alpine:3.11",         "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "alpine-3.12-glibc", "baseimage": "alpine:3.12",         "platforms": "linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "debian-8",          "baseimage": "debian:jessie-slim",  "platforms": "linux/amd64,linux/386,linux/arm/v5,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "debian-9",          "baseimage": "debian:stretch-slim", "platforms": "linux/amd64,linux/386,linux/arm/v5,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "debian-10",         "baseimage": "debian:buster-slim",  "platforms": "linux/amd64,linux/386,linux/arm/v5,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "ubuntu-16.04",      "baseimage": "ubuntu:xenial",       "platforms": "linux/amd64,linux/386,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "ubuntu-18.04",      "baseimage": "ubuntu:bionic",       "platforms": "linux/amd64,linux/386,linux/arm/v7,linux/arm64/v8" }'
+          - '{ "tag_prefix": "ubuntu-20.04",      "baseimage": "ubuntu:focal",        "platforms": "linux/amd64,linux/386,linux/arm/v7,linux/arm64/v8" }'
 
     steps:
       - name: Prepare
         id: prep
         run: |
           DOCKER_IMAGE=$GITHUB_REPOSITORY_OWNER/${GITHUB_REPOSITORY#*docker-}
+          # Determine the Docker container version.
           VERSION=github-ci
-          LABEL_VERSION=${VERSION}
           if [[ $GITHUB_REF == refs/tags/* ]]; then
             VERSION=${GITHUB_REF#refs/tags/}
-            LABEL_VERSION=${VERSION:1}
           elif [[ $GITHUB_REF == refs/heads/* ]]; then
             VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
             if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
               VERSION=edge
             fi
-            LABEL_VERSION=${VERSION}
           elif [[ $GITHUB_REF == refs/pull/* ]]; then
             VERSION=pr-${{ github.event.number }}
-            LABEL_VERSION=${VERSION}
+          else
+            echo "::error::Unexpected GITHUB_REF: $GITHUB_REF"
+            exit 1
           fi
+          # Determine the version to put in container label.
+          LABEL_VERSION=${VERSION}
+          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+            LABEL_VERSION=${VERSION:1}
+          fi
+          # Determine the Docker container tags.
           TAGS="${DOCKER_IMAGE}:${{ fromJSON(matrix.info).tag_prefix }}-${VERSION}"
           if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
             MINOR=${VERSION%.*}
             MAJOR=${MINOR%.*}
-            TAGS="$TAGS,${DOCKER_IMAGE}:${{ fromJSON(matrix.info).tag_prefix }}-${MINOR},${DOCKER_IMAGE}:${{ fromJSON(matrix.info).tag_prefix }}-${MAJOR},${DOCKER_IMAGE}:${{ fromJSON(matrix.info).tag_prefix }}"
+            TAGS="$TAGS,${DOCKER_IMAGE}:${{ fromJSON(matrix.info).tag_prefix }}-${MINOR}"
+            TAGS="$TAGS,${DOCKER_IMAGE}:${{ fromJSON(matrix.info).tag_prefix }}-${MAJOR}"
+            TAGS="$TAGS,${DOCKER_IMAGE}:${{ fromJSON(matrix.info).tag_prefix }}"
           elif [ "${{ github.event_name }}" = "push" ]; then
             TAGS="$TAGS,${DOCKER_IMAGE}:${{ fromJSON(matrix.info).tag_prefix }}-sha-${GITHUB_SHA::8}"
           fi
+          # Determine the Dockerfile to use.
+          if [[ "${{ fromJSON(matrix.info).tag_prefix }}" =~ alpine-* ]]; then
+            if [[ "${{ fromJSON(matrix.info).tag_prefix }}" =~ *-glibc ]]; then
+              DOCKERFILE=Dockerfile.alpine-glibc
+            else
+              DOCKERFILE=Dockerfile.alpine
+            fi
+          else
+            DOCKERFILE=Dockerfile.debian
+          fi
+          # Export outputs.
           echo ::set-output name=docker_image::${DOCKER_IMAGE}
+          echo ::set-output name=dockerfile::${DOCKERFILE}
           echo ::set-output name=version::${VERSION}
           echo ::set-output name=label_version::${LABEL_VERSION}
           echo ::set-output name=tags::${TAGS}
@@ -106,8 +127,8 @@ jobs:
         uses: docker/build-push-action@v2
         with:
           push: true
-          file: ${{ fromJSON(matrix.info).dockerfile }}
-          platforms: ${{ steps.prep.outputs.platforms }}
+          file: ${{ steps.prep.outputs.dockerfile }}
+          platforms: ${{ fromJSON(matrix.info).platforms }}
           tags: localhost:5000/${{ steps.prep.outputs.docker_image }}:github-ci
           build-args: |
             BASEIMAGE=${{ fromJSON(matrix.info).baseimage }}
